language: python

python:
    - 2.7

virtualenv:
    system_site_packages: true

before_install:
    - sh bin/check_signoff.sh

install:
    - npm install -g grunt-cli
    - npm install jshint
    - npm install

before_script:
    - jshint src/js/cilantro
    - git clone --branch demo git://github.com/cbmi/harvest-openmrs.git
    - pip install -r harvest-openmrs/requirements.txt
    - pip install uwsgi
    - uwsgi --master --enable-threads --http :8000 --chdir harvest-openmrs --wsgi-file wsgi.py &

script:
    - grunt test --verbose
